name       : haskell-fail
version    : 4.9.0.0
release    : 3
source     :
    - http://hackage.haskell.org/package/fail-4.9.0.0/fail-4.9.0.0.tar.gz : 6d5cdb1a5c539425a9665f740e364722e1d9d6ae37fbc55f30fe3dbbbb91d4a2
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains the Control.Monad.Fail module
description: |
    This package contains the Control.Monad.Fail module providing the MonadFail class that became available in base-4.9.0.0 for older base package versions.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
